FROM ceph/ceph:v18.2
ENV REFRESHED_AT 2024-030-18-01:02

RUN     mkdir /etc/selinux/ && touch /etc/selinux/config
RUN 	dnf update -y

# Cephfs environment
COPY 	micro-osd.sh /micro-osd.sh
COPY 	--chmod=755 cephfs_start.sh /cephfs_start.sh
RUN	mkdir /mycluster

CMD	/cephfs_start.sh
