FROM ceph/ceph:v19.2
ENV REFRESHED_AT 2025-03-12-01

RUN     mkdir /etc/selinux/ && touch /etc/selinux/config
#RUN 	dnf update -y

# Cephfs environment
COPY 	micro-osd.sh /micro-osd.sh
COPY 	--chmod=755 cephfs_start.sh /cephfs_start.sh
RUN	mkdir /mycluster

CMD	/cephfs_start.sh
