#Version: 0.0.1
ENV	REFRESHED_AT 2024-03-06:01
FROM 	quay.io/centos/centos:stream9

RUN	dnf install -y centos-release-ceph-reef.noarch 'dnf-command(config-manager)'
RUN	dnf update -y
RUN 	dnf install -y glibc-langpack-en iputils iproute iptables vim autofs rsync psmisc wget cifs-utils nfs-utils glibc-all-langpacks
RUN	dnf install -y git gdb gcc perl automake autoconf libtool flex bison strace

RUN	dnf install -y python3 python3-devel python3-tdb python3-tevent python3-pytest python3-pip python3-cephfs python3-cryptography python3-pyasn1
RUN	pip3 install tox pluggy

#Samba devel dependencies
RUN	dnf config-manager --enable crb
RUN	dnf install -y openssl-devel libxml2-devel libaio-devel libibverbs-devel librdmacm-devel readline-devel glib2-devel libacl-devel sqlite-devel fuse3-devel cups-devel dbus-devel docbook-style-xsl libcap-devel libtalloc-devel libtdb-devel libtevent-devel libxslt openldap-devel pam-devel perl-ExtUtils-MakeMaker perl-Parse-Yapp perl-Test-Simple popt-devel gnutls-devel libtirpc libtirpc-devel jansson-devel lvm2-devel userspace-rcu-devel libcmocka-devel libarchive-devel quota-devel libnsl2-devel rpcgen libcephfs-devel

# libldb-devel
RUN	dnf install -y samba samba-client
RUN	ln -sf /workspaces/samba_cephfs/bin /root/bin

RUN	useradd test1; (echo x; echo x)|smbpasswd -a test1
RUN	useradd test2; (echo x; echo x)|smbpasswd -a test2
RUN	groupadd sg; usermod -G sg test1

RUN	mkdir /local; chmod 777 /local

COPY	smb.conf /etc/samba/smb.conf

# Samba databases created.
# Now remove samba rpm packages
RUN	dnf remove -y samba

RUN	ln -s /workspaces/samba_cephfs /root/samba_cephfs
RUN	ln -s /workspaces/samba_cephfs/samba /root/samba
RUN	ln -s /workspaces/samba_cephfs/sit-test-cases /root/sit-test-cases

#Mount cephfs-fuse
RUN	dnf install -y ceph-fuse
RUN	rm -rf /etc/ceph && ln -sf /config/ceph /etc/ceph
RUN	mkdir /mnt-cephfs; chmod 777 /mnt-cephfs

CMD	while :; do sleep 1000; done
